[package]
name = "warehousebot"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
rustyline = "^15.0"
simple_logger = "5.0.0"


[lib]
name = "warehousebot"
path = "src/lib.rs"


[features]
default = ["with-file-history"]
with-file-history = []
